### ISSUE TITLE
Unexpected breaking changes in prerelease branch 

### ISSUE THREAD

**Issue by JDRkow** [TourmalineCore/TourmalineCore.AspNetCore.JwtAuthentication#57]
A pre-release version of the packages was prepared and tested on projects where they are used.

What we **expected** to see: that the new version of the package does not change or break the work of the projects where it is used. 

What we **actually got**: after updating the package and launching the project, the functionality of getting access tokens for different accounts was used.  And the functionality does not work because of a backend error related to the database. EF core cannot find relations in the refresh token table.

**Comment by iamvladislove** [comment]
After adding a generic identifier, backward compatibility was broken for the following reason - the table for storing refresh tokens changed the default name.  
Because of this, the relations between tables were broken in the database.  
I've tried different ways to fix the problem, but the easiest one is to set the default name for the refresh token table.
